# Build stage for young_astrologer_worker
FROM golang:1.21-alpine AS builder
WORKDIR /app/young_astrologer_worker
COPY . .
RUN go mod download
COPY ./cmd/worker/ .
RUN go build -o young_astrologer_worker main.go

FROM scratch AS young_astrologer_worker
COPY --from=builder /app/young_astrologer_worker/.env .env
COPY --from=builder /app/young_astrologer_worker/young_astrologer_worker /young_astrologer_worker

CMD ["./young_astrologer_worker"]