# Build stage for young_astrologer_worker
FROM golang:1.21-alpine AS young_astrologer_worker
WORKDIR /app/young_astrologer_worker
COPY . .
RUN go mod download
COPY ./cmd/worker/ .
RUN go build -o young_astrologer_worker main.go
CMD ["./young_astrologer_worker"]
RUN echo $YA_STORAGE_DATA_SOURCE